# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='文章名')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('keys', models.CharField(max_length=50, verbose_name='关键词')),
                ('created', models.DateField(auto_now_add=True, verbose_name='添加时间')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
        ),
    ]
