# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 00:58
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comments_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='content',
            field=markdownx.models.MarkdownxField(verbose_name='文章内容'),
        ),
    ]
